### ISSUE TITLE
프론트 개발할 때 참고하세요

### ISSUE THREAD

**Issue by leehj050211** [T-shaped-People/TCP-Frontend#5]
git pull 받을 때 마다 npm i --save 한 번씩 돌려주시고
비 로그인 시 자동으로 로그인 페이지로 이동하도록 패치 했으니
이제부터 프론트 개발할 때 마다 서버도 같이 키셔서 로그인해야 합니다.

귀찮으면 개발 환경에서는 무시하도록 패치 해드릴게요.

**Comment by min050410** [comment]
패치할 필요는 없는 것 같습니다. 한 페이지씩 만드는데는 문제 없어 보입니다. 감사합니다.
